# Dependencies
markdown: kramdown

kramdown:
  input: GFM

pygments: false

# Permalinks
permalink: '/announcements/:title'

# Setup
title: Vincent Bourdon
tagline: 'curriculum vitae'
description: 'mon cv'
url: http://www.evilznet.com

author:
  name: 'Vincent Bourdon'

paginate: 5
paginate_path: '/announcements/:num'

# Custom vars
version: 2.0.1

github:
  repo: https://github.com/evilz/evilz.github.io
