# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Evilz blog
email: evilz@evilznet.com
description: >
  Code for Human
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.evilznet.com" # the base hostname & protocol for your site
paginate:	10 # The number of posts to show per page on your homepage

name: 'Vincent Bourdon'
bio: >
  .Net Dev since 2001
author_image: "/assets/images/logo.jpg"
twitter_username: Evilznet
github_username:  evilz

# Google Analytics
analytics_id: "UA-2063306-2"

# Build settings
markdown: kramdown
permalink:          /:year/:month/:day/:title/

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate
  - nokogiri
  - fastimage

# Exclude list 
exclude: [Ignore, README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile] 
include: [_slides]
