#!/bin/bash

# enable error reporting to the console
set -e

SOURCE_BRANCH="Jekyll_Sources"
TARGET_BRANCH="HEAD:master"
REPO="https://${GH_TOKEN}@github.com/evilz/evilz.github.io.git"
CLONE_DIR="out"
JEKYLL_DIR="_site"

# git config
git config user.email "evilznet@gmail.com"
git config user.name "evilz"


# skip if build is triggered by pull request
if [ $TRAVIS_PULL_REQUEST == "true" ]; then
  echo "this is PR, exiting"
  exit 0
fi

# cleanup "CLONE_DIR"
rm -rf $CLONE_DIR
mkdir $CLONE_DIR

# clone remote repo to "CLONE_DIR"
#git clone $REPO $CLONE_DIR
#git checkout -b $SOURCE_BRANCH

# build with Jekyll into "CLONE_DIR"
bundle exec jekyll build

# push
cp CNAME $JEKYLL_DIR/CNAME
cd $JEKYLL_DIR


git checkout -b master
git add --all
git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"
#### git push --force origin $TARGET_BRANCH