#!/bin/bash

# enable error reporting to the console
set -e

SOURCE_BRANCH="Jekyll_Sources"
TARGET_BRANCH="master"
REPO="https://${GH_TOKEN}@github.com/evilz/evilz.github.io.git"
CLONE_DIR="out"
JEKYLL_DIR="_site"

# git config
git config user.email "evilznet@gmail.com"
git config user.name "evilz"


# skip if build is triggered by pull request
if [ $TRAVIS_PULL_REQUEST == "true" ]; then
  echo "this is PR, exiting"
  exit 0
fi

# cleanup "JEKYLL_DIR"
rm -rf $JEKYLL_DIR
mkdir $JEKYLL_DIR

# clone remote repo to "JEKYLL_DIR"
git clone $REPO --branch $TARGET_BRANCH $JEKYLL_DIR

# build with Jekyll into "CLONE_DIR"
bundle exec jekyll build

# push
cp CNAME $JEKYLL_DIR/CNAME
cd $JEKYLL_DIR


#git checkout -b travis
git add --all
git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"
git push --force origin $TARGET_BRANCH